### ISSUE TITLE
tweepy.error

### ISSUE THREAD

**Issue by alexynior28** [PaulSec/twittor#1]
Hi, could you please help me?

I have running implant.py on W7

[https://ibb.co/mVUZA6](https://ibb.co/mVUZA6)

and Twittor in Kali

[https://ibb.co/i30ViR](https://ibb.co/i30ViR)

In both I get an error.

**Comment by PaulSec** [comment]
Hey there, 

Sorry for just noticing your issue. 
Could you past screenshots in here as well? I prefer not clicking on shorted links coming from the Internet :-) 

Cheers,

**Comment by PaulSec** [comment]
Closed since I didn't get any answer. Feel free to re-open it. 

Cheers
